server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # SPA uchun (agar boshqa sahifalar bo'lsa)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Statik fayllar uchun cache
    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Xatoliklarni boshqarish
    error_page 404 /index.html;
    error_page 500 502 503 504 /50x.html;
}